# Generated by Django 2.2.6 on 2020-01-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_news_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=550)),
                ('already_read', models.BooleanField()),
            ],
        ),
    ]
