# Generated by Django 3.0.2 on 2020-01-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_path',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
