# Generated by Django 3.0.2 on 2020-01-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_news_image_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AddField(
            model_name='news',
            name='portal',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=250),
        ),
    ]
