# Generated by Django 3.0.2 on 2020-03-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_auto_20200219_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Portal'),
        ),
    ]
